// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHjE-f2HGUQtnvhzQZ638XCpXTio_kj18',
    appId: '1:398845168370:web:5c26febdb948c017291e6b',
    messagingSenderId: '398845168370',
    projectId: 'elytron-d2b-dev',
    authDomain: 'elytron-d2b-dev.firebaseapp.com',
    storageBucket: 'elytron-d2b-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC67gKcL8eDjTLcj4UpzucUToTe5bqUojI',
    appId: '1:398845168370:android:c64b436b29b89a35291e6b',
    messagingSenderId: '398845168370',
    projectId: 'elytron-d2b-dev',
    storageBucket: 'elytron-d2b-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu75Zl_Z0OWxiFKZlco7-QYvYg9f3OtVQ',
    appId: '1:398845168370:ios:a91dea4ab9255a45291e6b',
    messagingSenderId: '398845168370',
    projectId: 'elytron-d2b-dev',
    storageBucket: 'elytron-d2b-dev.firebasestorage.app',
    iosBundleId: 'com.elytronsecurity.elytronDash2board',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu75Zl_Z0OWxiFKZlco7-QYvYg9f3OtVQ',
    appId: '1:398845168370:ios:b3559863b19be6cb291e6b',
    messagingSenderId: '398845168370',
    projectId: 'elytron-d2b-dev',
    storageBucket: 'elytron-d2b-dev.firebasestorage.app',
    iosBundleId: 'dash2board',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHjE-f2HGUQtnvhzQZ638XCpXTio_kj18',
    appId: '1:398845168370:web:ec2cc01b0934b328291e6b',
    messagingSenderId: '398845168370',
    projectId: 'elytron-d2b-dev',
    authDomain: 'elytron-d2b-dev.firebaseapp.com',
    storageBucket: 'elytron-d2b-dev.firebasestorage.app',
  );
}
